- name: Create host object
  connection: network_cli
  gather_facts: true
- hosts: all

  checkpoint_host:
    name: attacker
    ip_address: 192.168.0.15

- name: Delete host object
  checkpoint_host:
    name: attacker
    state: absent
