- name: Collect BIG-IP facts
  connection: network_cli
  gather_facts: true
- hosts: all
  bigip_facts:
    server: 172.30.8.50
    user: f5lab
    password: F5Lab0ratory
    include:
      - interface
      - vlan
  delegate_to: localhost
