- name: collect default set of facts
  connection: network_cli
  gather_facts: true
- hosts: all
  junos_facts:

- name: collect default set of facts and configuration
  junos_facts:
    gather_subset: config

- name: Gather legacy and resource facts
  junos_facts:
    gather_subset: all
    gather_network_resources: all
