# configure ACL ANSIBLE
- nxos_acl:
    name: ANSIBLE
      connection: network_cli
  gather_facts: true
- hosts: all
    seq: 10
    action: permit
    proto: tcp
    src: 192.0.2.1/24
    dest: any
    state: present
